# Generated by Django 3.2.7 on 2021-11-17 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_game_nerd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nerd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='main_app.nerd'),
        ),
    ]
